/* ==================================== JUCER_BINARY_RESOURCE ====================================

   This is an auto-generated file: Any edits you make may be overwritten!

*/

#include <cstring>

namespace BinaryData
{

//================== README.md ==================
static const unsigned char temp_binary_data_6[] =
"# Faust API\n"
"\n"
"This API allows to interact with a Faust object and its associated audio engine at a high level. The idea is that all the audio part of the app is implemented in Faust allowing developers to focus on the design of the application itself. \n"
"\n"
"### Application Set-Up\n"
"\n"
"Import `DspFaust.h` and `DspFaust.cpp` in your project (this can be done simply by dragging these files in your project tree). Then, import `DspFaust.h` (`#include \"DspFaust.h\"`) in the file where you want to create/control the Faust object. \n"
"\n"
"### Using the C++ API\n"
"\n"
"The current Faust API is designed to seamlessly integrate to the life cycle of an app. It is accessible through a single `DspFaust` object. The constructor of that object is used to set the sampling rate and the buffer size:\n"
"\n"
"\tDspFaust* dspFaust = new DspFaust(SR, BS);\n"
"\n"
"The `start()` method is used to start the audio computing. Similarly, `stop()` can be called to stop the audio computing.\n"
"\n"
"It is possible to interact with the different parameters of the Faust object by using the `setParamValue` method. Two versions of this method exist: one where the parameter can be selected by its address and one where it can be selected using its ID."
" The [Parameters List](#parameters-list) section gives a list of the addresses and corresponding IDs of the current Faust object.\n"
"\n"
"If your Faust object is polyphonic (e.g. if you used the `-nvoices` option when generating this API), then you can use the MIDI polyphony methods like `keyOn`, `keyOff`, etc.\n"
"\n"
"It is possible to change the parameters of polyphonic voices independently using the `setVoiceParamValue` method. This method takes as one of its arguments the address to the voice returned by `keyOn` or `newVoice` when it is called. E.g:\n"
"\n"
"\tuintptr_t voiceAddress = dspFaust->keyOn(70, 100);\n"
"\tdspFaust->setVoiceParamValue(1, voiceAddress, 214);\n"
"\tdspFaust->keyOff(70);\n"
"\t\n"
"In the example above, a new note is created and its parameter ID 1 is modified. This note is then terminated. Note that parameters addresses (path) are different for independent voices than when using `setParamValue`. The list of these addresses is p"
"rovided in a separate sub-section of the [Parameters List](#parameters-list) section.\n"
"\n"
"Finally, note that new voices don't necessarily have to be created using `keyOn`. Indeed, you might choose to just use the `newVoice` method for that:\n"
"\n"
"\tuintptr_t voiceAddress = dspFaust->newVoice();\n"
"\tdspFaust->setVoiceParamValue(1, voiceAddress, 214);\n"
"\tdspFaust->deleteVoice(voiceAddress);\n"
"\n"
"This is particularly useful when making applications where each finger of the user is an independent sound that doesn't necessarily has a pitch.\n"
"\n"
"In case you would like to use the built-in accelerometer or gyroscope of your device to control some of the parameters of your Faust object, all you have to do is to send the raw accelerometer data to it by using the `propagateAcc` or `propagateGyr` "
"for the gyroscope. After that, mappings can be configured directly from the Faust code using [this technique](#using-built-in-sensors-to-control-parameters) or using the `setAccConverter` and `setGyrConverter` method.\n"
"\n"
"## Parameters List\n"
"\n"
"### Main Parameters\n"
"\n"
"* **0**: `/faug/osc_bank/freq`\n"
"* **1**: `/faug/osc_bank/oscOnePower`\n"
"* **2**: `/faug/osc_bank/oscTwoPower`\n"
"* **3**: `/faug/osc_bank/oscThreePower`\n"
"* **4**: `/faug/osc_bank/oscOneGain`\n"
"* **5**: `/faug/osc_bank/oscTwoGain`\n"
"* **6**: `/faug/osc_bank/oscThreeGain`\n"
"* **7**: `/faug/osc_bank/waveOne`\n"
"* **8**: `/faug/osc_bank/waveTwo`\n"
"* **9**: `/faug/osc_bank/waveThree`\n"
"* **10**: `/faug/osc_bank/rangeOne`\n"
"* **11**: `/faug/osc_bank/rangeTwo`\n"
"* **12**: `/faug/osc_bank/rangeThree`\n"
"* **13**: `/faug/osc_bank/globalDetune`\n"
"* **14**: `/faug/osc_bank/detuneTwo`\n"
"* **15**: `/faug/osc_bank/detuneThree`\n"
"* **16**: `/faug/envelope/eAttack`\n"
"* **17**: `/faug/envelope/eDecay`\n"
"* **18**: `/faug/envelope/eSustain`\n"
"* **19**: `/faug/envelope/gate`\n"
"* **20**: `/faug/filter/cutoff`\n"
"* **21**: `/faug/filter/emphasis`\n"
"* **22**: `/faug/filter/contourAmount`\n"
"* **23**: `/faug/filter/fAttack`\n"
"* **24**: `/faug/filter/fDecay`\n"
"* **25**: `/faug/filter/fSustain`\n"
"* **26**: `/faug/filter/gate`\n"
"* **27**: `/faug/noise/noiseType`\n"
"* **28**: `/faug/noise/noiseOn`\n"
"* **29**: `/faug/noise/noiseGain`\n"
"* **30**: `/faug/feedbackGain`\n"
"* **31**: `/faug/feedbackOn`\n"
"* **32**: `/faug/load`\n"
"\n"
"\n"
"## API Reference\n"
"\n"
"### `DspFaust(bool auto_connect = true)`\n"
"Default constructor, to be used wih audio drivers that impose their sample rate and buffer size (like JACK and JUCE).\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `auto_connect`: whether to automatically connect audio outpus to the hardware (usable with JACK)\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `DspFaust(int SR, int BS, bool auto_connect = true)`\n"
"Constructor.\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `SR`: sampling rate\n"
"\n"
"* `BS`: buffer size\n"
"\n"
"* `auto_connect`: whether to automatically connect audio outputs to the hardware (usable with JACK)\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `DspFaust(const string& dsp_content, int SR, int BS, bool auto_connect = true)`\n"
"Constructor.\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `dsp_content`: the DSP as a file or string\n"
"\n"
"* `SR`: sampling rate\n"
"\n"
"* `BS`: buffer size\n"
"\n"
"* `auto_connect`: whether to automatically connect audio outputs to the hardware (usable with JACK)\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `bool start()`\n"
"Start the audio processing.\n"
"\n"
"\n"
"\n"
"Returns `true` if successful and `false` if not.\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `void stop()`\n"
"Stop the audio processing.\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `bool isRunning()`\n"
"Returns `true` if audio is running.\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `long keyOn(int pitch, int velocity)`\n"
"Instantiate a new polyphonic voice. This method can\n"
"\n"
"only be used if the `-nvoices` flag has been\n"
"\n"
"provided before compilation.\n"
"\n"
"\n"
"\n"
"`keyOn` will return 0 if the Faust object is not\n"
"\n"
"polyphonic or the address to the allocated voice as\n"
"\n"
"an `uintptr_t` otherwise. This value can be used later with\n"
"\n"
"[`setVoiceParamValue`](#setvoiceparamvalue) or\n"
"\n"
"[`getVoiceParamValue`](#getvoiceparamvalue) to access\n"
"\n"
"the parameters of a specific voice.\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `pitch`: MIDI note number (0-127)\n"
"\n"
"* `velocity`: MIDI velocity (0-127)\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `int keyOff(int pitch)`\n"
"De-instantiate a polyphonic voice. This method can\n"
"\n"
"only be used if the `-nvoices` flag has been\n"
"\n"
"provided before compilation.\n"
"\n"
"\n"
"\n"
"`keyOff` will return 0 if the object is not polyphonic\n"
"\n"
"and 1 otherwise.\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `pitch`: MIDI note number (0-127), should be the same\n"
"\n"
"as the one used for `keyOn`\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `uintptr_t newVoice()`\n"
"Instantiate a new polyphonic voice. This method can\n"
"\n"
"only be used if `-nvoices` flag has been\n"
"\n"
"provided before compilation.\n"
"\n"
"\n"
"\n"
"`newVoice` will return 0 if the Faust object is not\n"
"\n"
"polyphonic or the address to the allocated voice as\n"
"\n"
"a `uintptr_t` otherwise. This value can be used later with\n"
"\n"
"`setVoiceParamValue`, `getVoiceParamValue` or\n"
"\n"
"`deleteVoice` to access the parameters of a specific\n"
"\n"
"voice.\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `int deleteVoice(uintptr_t voice)`\n"
"De-instantiate a polyphonic voice. This method can\n"
"\n"
"only be used if `-nvoices` flag has been\n"
"\n"
"provided before compilation.\n"
"\n"
"\n"
"\n"
"`deleteVoice` will return 0 if the object is not polyphonic\n"
"\n"
"and 1 otherwise.\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `voice`: the address of the voice given by `newVoice` or `keyOn`\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `void allNotesOff(bool hard = false)`\n"
"Terminates all the active voices, gently (with release when hard = false or immediately when hard = true).\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `void propagateMidi(int count, double time, int type, int channel, int data1, int data2)`\n"
"Take a raw MIDI message and propagate it to the Faust\n"
"\n"
"DSP object. This method can be used concurrently with\n"
"\n"
"[`keyOn`](#keyOn) and [`keyOff`](#keyOff).\n"
"\n"
"\n"
"\n"
"`propagateMidi` can only be used if `-nvoices` flag has been\n"
"\n"
"provided before compilation.\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `count`: size of the message (1-3)\n"
"\n"
"* `time`: time stamp\n"
"\n"
"* `type`: message type (byte)\n"
"\n"
"* `channel`: channel number\n"
"\n"
"* `data1`: first data byte (should be `null` if `count<2`)\n"
"\n"
"* `data2`: second data byte (should be `null` if `count<3`)\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `const char* getJSONUI()`\n"
"Returns the JSON description of the UI of the Faust object.\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `const char* getJSONMeta()`\n"
"Returns the JSON description of the metadata of the Faust object.\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `void buildUserInterface(UI* ui_interface)`\n"
"Calls the polyphonic or monophonic buildUserInterface with the ui_interface parameter.\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `ui_interface`: an UI* object\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `int getParamsCount()`\n"
"Returns the number of parameters of the Faust object.\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `void setParamValue(const char* address, float value)`\n"
"Set the value of one of the parameters of the Faust\n"
"\n"
"object in function of its address (path).\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `address`: address (path) of the parameter\n"
"\n"
"* `value`: value of the parameter\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `void setParamValue(int id, float value)`\n"
"Set the value of one of the parameters of the Faust\n"
"\n"
"object in function of its id.\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `id`: id of the parameter\n"
"\n"
"* `value`: value of the parameter\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `float getParamValue(const char* address)`\n"
"Returns the value of a parameter in function of its\n"
"\n"
"address (path).\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `address`: address (path) of the parameter\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `float getParamValue(int id)`\n"
"Returns the value of a parameter in function of its id.\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `id`: id of the parameter\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `void setVoiceParamValue(const char* address, uintptr_t voice, float value)`\n"
"Set the value of one of the parameters of the Faust\n"
"\n"
"object in function of its address (path) for a specific voice.\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `address`: address (path) of the parameter\n"
"\n"
"* `voice`: address of the polyphonic voice (retrieved from `keyOn`)\n"
"\n"
"* `value`: value of the parameter\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `void setVoiceParamValue(int id, uintptr_t voice, float value)`\n"
"Set the value of one of the parameters of the Faust\n"
"\n"
"object in function of its id for a specific voice.\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `id`: id of the parameter\n"
"\n"
"* `voice`: address of the polyphonic voice (retrieved from `keyOn`)\n"
"\n"
"* `value`: value of the parameter\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `float getVoiceParamValue(const char* address, uintptr_t voice)`\n"
"Returns the value of a parameter in function of its\n"
"\n"
"address (path) for a specific voice.\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `address`: address (path) of the parameter\n"
"\n"
"* `voice`: address of the polyphonic voice (retrieved from `keyOn`)\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `float getVoiceParamValue(int id, uintptr_t voice)`\n"
"Returns the value of a parameter in function of its\n"
"\n"
"id for a specific voice.\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `id`: id of the parameter\n"
"\n"
"* `voice`: address of the polyphonic voice (retrieved\n"
"\n"
"from `keyOn`)\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `const char* getParamAddress(int id)`\n"
"Returns the address (path) of a parameter in function of its ID.\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `id`: id of the parameter\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `const char* getVoiceParamAddress(int id, uintptr_t voice)`\n"
"Returns the address (path) of a parameter in function of its ID.\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `id`: id of the parameter\n"
"\n"
"* `voice`: address of the polyphonic voice (retrieved from `keyOn`)\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `float getParamMin(const char* address)`\n"
"Returns the minimum value of a parameter in function of\n"
"\n"
"its address (path).\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `address`: address (path) of the parameter\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `float getParamMin(int id)`\n"
"Returns the minimum value of a parameter in function\n"
"\n"
"of its ID.\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `id`: id of the parameter\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `float getParamMax(const char* address)`\n"
"Returns the maximum value of a parameter in function of\n"
"\n"
"its address (path).\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `address`: address (path) of the parameter\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `float getParamMax(int id)`\n"
"Returns the maximum value of a parameter in function\n"
"\n"
"of its ID.\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `id`: id of the parameter\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `float getParamInit(const char* address)`\n"
"Returns the default value of a parameter in function of\n"
"\n"
"its address (path).\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `address`: address (path) of the parameter\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `float getParamInit(int id)`\n"
"Returns the default value of a parameter in function\n"
"\n"
"of its ID.\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `id`: id of the parameter\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `const char* getMetadata(const char* address, const char* key)`\n"
"Returns the metadataof a parameter in function of\n"
"\n"
"its address (path) and the metadata key.\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `address`: address (path) of the parameter\n"
"\n"
"* `key`: the metadata key\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `const char* getMetadata(int id, const char* key)`\n"
"Returns the metadataof a parameter in function of\n"
"\n"
"its iD and the metadata key.\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `id`: id of the parameter\n"
"\n"
"* `key`: the metadata key\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `void propagateAcc(int acc, float v)`\n"
"Propagate the RAW value of a specific accelerometer\n"
"\n"
"axis to the Faust object.\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `acc`: the accelerometer axis (**0**: x, **1**: y, **2**: z)\n"
"\n"
"* `v`: the RAW accelerometer value in m/s\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `void setAccConverter(int p, int acc, int curve, float amin, float amid, float amax)`\n"
"Set the conversion curve for the accelerometer.\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `id`: the UI parameter id\n"
"\n"
"* `acc`: the accelerometer axis (**0**: x, **1**: y, **2**: z)\n"
"\n"
"* `curve`: the curve (**0**: up, **1**: down, **2**: up and down)\n"
"\n"
"* `amin`: mapping min point\n"
"\n"
"* `amid`: mapping middle point\n"
"\n"
"* `amax`: mapping max point\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `void propagateGyr(int gyr, float v)`\n"
"Propagate the RAW value of a specific gyroscope\n"
"\n"
"axis to the Faust object.\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `gyr`: the gyroscope axis (**0**: x, **1**: y, **2**: z)\n"
"\n"
"* `v`: the RAW gyroscope value in m/s\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `void setGyrConverter(int p, int gyr, int curve, float amin, float amid, float amax)`\n"
"Set the conversion curve for the gyroscope.\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `id`: the UI parameter id\n"
"\n"
"* `gyr`: the gyroscope axis (**0**: x, **1**: y, **2**: z)\n"
"\n"
"* `curve`: the curve (**0**: up, **1**: down, **2**: up and down)\n"
"\n"
"* `amin`: mapping min point\n"
"\n"
"* `amid`: mapping middle point\n"
"\n"
"* `amax`: mapping max point\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `float getCPULoad()`\n"
"Returns the CPU load (between 0 and 1.0).\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `void configureOSC(int xmit, int inport, int outport, int errport, const char* address)`\n"
"Change the OSC configuration.\n"
"\n"
"\n"
"\n"
"#### Arguments\n"
"\n"
"\n"
"\n"
"* `xmit`: the xmit state (off-0 all-1 alias-2)\n"
"\n"
"* `inport`: the input port number\n"
"\n"
"* `outport`: the output port number\n"
"\n"
"* `errport`: the error port number\n"
"\n"
"* `address`: the destination IP address\n"
"\n"
"\n"
"---\n"
"\n"
"\n"
"### `bool isOSCOn()`\n"
"Return OSC Status.\n"
"\n"
"\n"
"---\n"
"\n";

const char* README_md = (const char*) temp_binary_data_6;
}
